[project]
name="hyperlocal-platform"
version = "2.0.2"
dependencies=[
    "pyjwt",
    "cryptography",
    "argon2-cffi",
    "orjson",
    "icecream",
    "pytz",
    "pydantic",
    "redis",
    "sqlalchemy"
]